<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <UseWPF>True</UseWPF>
    <ApplicationIcon>VCG211487178498.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="avcodec-63.dll" />
    <None Remove="avdevice-63.dll" />
    <None Remove="avfilter-12.dll" />
    <None Remove="avformat-63.dll" />
    <None Remove="avutil-61.dll" />
    <None Remove="swresample-7.dll" />
    <None Remove="swscale-10.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="avcodec-63.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avdevice-63.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avfilter-12.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avformat-63.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="avutil-61.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="swresample-7.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="swscale-10.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="VCG211487178498.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="9.0.1.1" />
    <PackageReference Include="SharpGen.Runtime" Version="2.4.2-beta" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
  </ItemGroup>

</Project>